# Generated by Django 3.0.2 on 2020-03-06 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_auto_20200306_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('metastory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='projects.MetaStory')),
                ('userstory_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='userstory_id')),
            ],
            bases=('projects.metastory',),
        ),
    ]
