# Generated by Django 3.0.2 on 2020-03-07 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epics', '0001_initial'),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='epic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='userstory_epic', to='epics.Epic'),
        ),
    ]
