# Generated by Django 3.0.3 on 2020-03-18 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('stories', '0003_auto_20200309_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='project_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userstory_project_code', to='projects.Project'),
        ),
    ]
