# Generated by Django 3.0.3 on 2020-03-18 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epics', '0001_initial'),
        ('stories', '0005_auto_20200318_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='epic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userstory_epic', to='epics.Epic'),
        ),
    ]
