# Generated by Django 3.0.2 on 2020-03-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_userstory_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='comment',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
