# Generated by Django 3.0.2 on 2020-03-21 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('stories', '0008_userstory_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userstory_comment', to='comments.Comment'),
        ),
    ]
