# Generated by Django 3.0.2 on 2020-03-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('stories', '0009_auto_20200321_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='comment',
        ),
        migrations.AddField(
            model_name='userstory',
            name='comment',
            field=models.ManyToManyField(null=True, related_name='userstory_comment', to='comments.Comment'),
        ),
    ]
