# Generated by Django 3.0.2 on 2020-03-23 17:13

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200323_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=projects.models.project_directory_path)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='documents',
            field=models.ManyToManyField(to='projects.Documents'),
        ),
    ]
