# Generated by Django 3.0.2 on 2020-03-06 13:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('projects', '0002_auto_20200303_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to='users.Profile'),
        ),
        migrations.CreateModel(
            name='MetaStory',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=250)),
                ('importance', models.CharField(default='Low', max_length=8)),
                ('state', models.CharField(default='OPEN', max_length=15)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='users.Profile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='users.Profile')),
                ('project_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_code', to='projects.Project', to_field='code')),
            ],
        ),
    ]
