# Generated by Django 3.0.2 on 2020-03-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200306_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='documents',
        ),
    ]
