# Generated by Django 3.0.2 on 2020-03-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epic',
            name='assignee',
        ),
    ]
