# Generated by Django 3.0.2 on 2020-02-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.IntegerField(auto_created=True, db_index=True, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(help_text='Required. 30 characters or fewer. Letters, numbers and /./-/_ characters', max_length=255, unique=True, verbose_name='username')),
                ('full_name', models.CharField(blank=True, max_length=256, verbose_name='full name')),
                ('email', models.EmailField(blank=True, max_length=255, unique=True, verbose_name='email address')),
            ],
        ),
    ]
