# Generated by Django 3.0.3 on 2020-03-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklogs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='work_log',
            field=models.ManyToManyField(to='worklogs.Worklog'),
        ),
    ]
