# Generated by Django 3.0.5 on 2020-04-11 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_remove_comment_owner_usr'),
        ('worklogs', '0005_auto_20200404_1419'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0003_auto_20200406_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='solved',
        ),
        migrations.AddField(
            model_name='issue',
            name='comment',
            field=models.ManyToManyField(related_name='issue_comment', to='comments.Comment'),
        ),
        migrations.AddField(
            model_name='issue',
            name='work_log',
            field=models.ManyToManyField(to='worklogs.Worklog'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_assignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
