# Generated by Django 3.0.3 on 2020-03-28 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='log date')),
                ('logged_hour', models.IntegerField(verbose_name='logged hours')),
            ],
            options={
                'verbose_name': 'worklog',
                'verbose_name_plural': 'worklogs',
            },
        ),
    ]
