# Generated by Django 3.0.3 on 2020-03-29 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_work_log'),
        ('worklogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='log_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name=''),
        ),
    ]
