# Generated by Django 3.0.3 on 2020-04-04 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklogs', '0002_worklog_log_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='log_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 14, 12, 58, 739829), verbose_name='log date'),
        ),
    ]
