# Generated by Django 3.0.3 on 2020-04-04 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklogs', '0003_auto_20200404_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='log_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='log date'),
        ),
    ]
