# Generated by Django 3.0.3 on 2020-04-04 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('worklogs', '0004_auto_20200404_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='log_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='log date'),
        ),
    ]
