# Generated by Django 3.0.2 on 2020-03-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_owner_usr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='owner_usr',
        ),
    ]
