# Generated by Django 3.0.2 on 2020-03-22 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epics', '0001_initial'),
        ('tasks', '0002_auto_20200309_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='epic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_epic', to='epics.Epic'),
        ),
    ]
