# Generated by Django 3.0.5 on 2020-04-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklogs', '0005_auto_20200404_1419'),
        ('comments', '0003_remove_comment_owner_usr'),
        ('tasks', '0006_auto_20200411_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='acceptance',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.ManyToManyField(related_name='task_comment', to='comments.Comment'),
        ),
        migrations.AddField(
            model_name='task',
            name='work_log',
            field=models.ManyToManyField(to='worklogs.Worklog'),
        ),
    ]
